src/Demo.BeerVoting.Frontend/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Demo.BeerVoting.Frontend.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

src/Demo.BeerVoting.Frontend/Pages/Index.cshtml.cs
using Demo.BeerVoting.Frontend.Dtos.Responses;
using Demo.BeerVoting.Frontend.Services;

using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QRCoder;

using static QRCoder.PayloadGenerator;

namespace Demo.BeerVoting.Frontend.Pages;

public class IndexModel : PageModel
{
    private readonly IBackendService _backendService;
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(IBackendService backendService, ILogger<IndexModel> logger)
    {
        _backendService = backendService;
        _logger = logger;
    }

    public List<GetFavoriteBeerResponse> FavoriteBeers { get; set; } = null!;

    public async Task OnGet()
    {
        _logger.LogInformation("Get total votes");
        int totalVotes = await _backendService.GetTotalRatings();
        this.ViewData.Add("TotalRatings", totalVotes);
        _logger.LogInformation("Got {count} total votes", totalVotes);

        _logger.LogInformation("Get favorite beers");
        FavoriteBeers = await _backendService.GetFavoriteBeers();
        _logger.LogInformation("Got {count} beers", FavoriteBeers.Count);
    }

    public async Task<ActionResult> OnPostRate(Guid id, int value)
    {
        _logger.LogInformation("Rate beer with id {beerId}", id);

        await _backendService.RateFavoriteBeer(id, Convert.ToDouble(value));

        return RedirectToPage();
    }

    public string GetQrCodeForUrl()
    {
        Url generator = new Url(Request.GetDisplayUrl());
        string payload = generator.ToString();

        QRCodeGenerator qrGenerator = new QRCodeGenerator();
        QRCodeData qrCodeData = qrGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.Q);

        using SvgQRCode qrCode = new SvgQRCode(qrCodeData);
        string qrCodeAsSvg = qrCode.GetGraphic(12);

        return qrCodeAsSvg;
    }
}

src/Demo.BeerVoting.Frontend/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@if (Model.FavoriteBeers == null)
{
    <h2>No beers found.</h2>
}
else
{
    <form method="post">
    <table style="width: 100%;" class="beerTable">
        <thead>
            <tr>
                <th>Beer</th>
                <th>Rating</th>
                <th class="rateButtonContainerHeader">Rate beer</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var beer in Model.FavoriteBeers)
                {
                    <tr>
                        @if (string.IsNullOrEmpty(beer.Nickname))
                        {
                            <td>
                                <span>@beer.Name</span><br />
                                <span class="text-muted"><i>by</i> @beer.Brewery</span>
                            </td>
                        }
                        else
                        {
                            <td>
                                <span>@beer.Name (@beer.Nickname)</span><br />
                                <span class="text-muted"><i>by</i> @beer.Brewery</span>
                            </td>
                        }
                        <td>@beer.Score</td>
                        <td class="rateButtonContainer">
                            <input type="submit" value="1" asp-page-handler="Rate" asp-route-id="@beer.Id" asp-route-value="1"
                                class="btn btn-primary rateButton" />
                            <input type="submit" value="2" asp-page-handler="Rate" asp-route-id="@beer.Id" asp-route-value="2"
                                class="btn btn-primary rateButton" />
                            <input type="submit" value="3" asp-page-handler="Rate" asp-route-id="@beer.Id" asp-route-value="3"
                                class="btn btn-primary rateButton" />
                            <input type="submit" value="4" asp-page-handler="Rate" asp-route-id="@beer.Id" asp-route-value="4"
                                class="btn btn-primary rateButton" />
                            <input type="submit" value="5" asp-page-handler="Rate" asp-route-id="@beer.Id" asp-route-value="5"
                                class="btn btn-primary rateButton" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
}

<div class="qr-container">
    <div class="qr-toggle"><a href="#" onclick="return false;">Show QR Code</a></div>
    <div class="qr-code" style="display: none;">@Html.Raw(Model.GetQrCodeForUrl())</div>
</div>

@section Css {
    .qr-container {
        margin: 40px 0 0;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
}

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            document.querySelectorAll(".qr-container").forEach(function (element) {
                element.addEventListener("click", function () {
                    var qrCode = document.querySelector(".qr-code");
                    if (qrCode.style.display === "none") {
                        qrCode.style.display = "block";
                    } else {
                        qrCode.style.display = "none";
                    }
                });
            });
        });
    </script>
}

src/Demo.BeerVoting.Frontend/Pages/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.BeerVoting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/Demo.BeerVoting.styles.css" asp-append-version="true" /> *@
    @Html.Raw(JavaScriptSnippet.FullScript)
    <style>
        @await RenderSectionAsync("Css", required: false)
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Demo.BeerVoting</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @* <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul> *@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <span class="nav-link text-dark">Total votes: @ViewData["TotalRatings"]</span>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @(DateTime.UtcNow.Year) - Demo.BeerVoting
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>